# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32b42a9fe2f02b2fe9a53c4b5b6e3d2f8bee17722d7a089cc33150fa7bfde6bbe79e043d662d2b45174bd1b4646ed30122de1e479496a3375fad5011a6cf1ab4

test:
  secret_key_base: 96811691db4645383746fd7ab92b047139a20e35ec72b8d9f52d01e420049b6f23c700e2c78a3eb4c1164c836733a09a12e2d089b82a3ffc7ad4e870dbefdf6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
